/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetPlatforms { 
    /**
     * asset platform id
     */
    id?: string;
    /**
     * chainlist\'s chain id
     */
    chain_identifier?: number | null;
    /**
     * chain name
     */
    name?: string;
    /**
     * chain shortname
     */
    shortname?: string;
    /**
     * chain native coin id
     */
    native_coin_id?: string;
    /**
     * image of the asset platform
     */
    image?: string;
}

