/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Categories { 
    /**
     * category id
     */
    id?: string;
    /**
     * category name
     */
    name?: string;
    /**
     * category market cap
     */
    market_cap?: number;
    /**
     * category market cap change in 24 hours
     */
    market_cap_change_24h?: number;
    /**
     * category description
     */
    content?: string;
    /**
     * ids of top 3 coins in the category
     */
    top_3_coins_id?: Array<string>;
    /**
     * images of top 3 coins in the category
     */
    top_3_coins?: Array<string>;
    /**
     * category volume in 24 hours
     */
    volume_24h?: number;
    /**
     * category last updated time
     */
    updated_at?: string;
}

