/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin public interest stats
 */
export interface CoinsHistoricalDataPublicInterestStats { 
    /**
     * coin alexa rank
     */
    alexa_rank?: number;
    /**
     * coin bing matches
     */
    bing_matches?: number;
}

