/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoinsHistoricalDataMarketDataTotalVolume } from './coins-historical-data-market-data-total-volume';
import { CoinsHistoricalDataMarketDataMarketCap } from './coins-historical-data-market-data-market-cap';
import { CoinsHistoricalDataMarketDataCurrentPrice } from './coins-historical-data-market-data-current-price';


/**
 * coin market data
 */
export interface CoinsHistoricalDataMarketData { 
    current_price?: CoinsHistoricalDataMarketDataCurrentPrice;
    market_cap?: CoinsHistoricalDataMarketDataMarketCap;
    total_volume?: CoinsHistoricalDataMarketDataTotalVolume;
}

