/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin code additions deletions 4 weeks
 */
export interface CoinsHistoricalDataDeveloperDataCodeAdditionsDeletions4Weeks { 
    additions?: number;
    deletions?: number;
}

