/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin ticker exchange
 */
export interface CoinsDataBaseTickersInnerMarket { 
    /**
     * coin ticker exchange name
     */
    name?: string;
    /**
     * coin ticker exchange identifier
     */
    identifier?: string;
    /**
     * coin ticker exchange trading incentive
     */
    has_trading_incentive?: boolean;
}

