/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin 24h market cap change in percentage
 */
export interface CoinsDataBaseMarketDataMarketCapChangePercentage24hInCurrency { 
    btc?: number;
    eur?: number;
    usd?: number;
}

