/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoinsDataBaseLinksReposUrl } from './coins-data-base-links-repos-url';


/**
 * links
 */
export interface CoinsDataBaseLinks { 
    /**
     * coin website url
     */
    homepage?: Array<string>;
    /**
     * coin whitepaper url
     */
    whitepaper?: Array<string>;
    /**
     * coin block explorer url
     */
    blockchain_site?: Array<string>;
    /**
     * coin official forum url
     */
    official_forum_url?: Array<string>;
    /**
     * coin chat url
     */
    chat_url?: Array<string>;
    /**
     * coin announcement url
     */
    announcement_url?: Array<string>;
    /**
     * coin twitter handle
     */
    twitter_screen_name?: string;
    /**
     * coin facebook username
     */
    facebook_username?: string;
    /**
     * coin bitcointalk thread identifier
     */
    bitcointalk_thread_identifier?: string;
    /**
     * coin telegram channel identifier
     */
    telegram_channel_identifier?: string;
    /**
     * coin subreddit url
     */
    subreddit_url?: string;
    repos_url?: CoinsDataBaseLinksReposUrl;
}

