/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin ticker exchange
 */
export interface CoinsTickersTickersInnerMarket { 
    /**
     * exchange name
     */
    name: string;
    /**
     * exchange identifier
     */
    identifier: string;
    /**
     * exchange trading incentive
     */
    has_trading_incentive: boolean;
    /**
     * exchange image url
     */
    logo?: string;
}

