/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoinsDataBaseTickersInnerConvertedVolume } from './coins-data-base-tickers-inner-converted-volume';
import { CoinsTickersTickersInnerMarket } from './coins-tickers-tickers-inner-market';
import { CoinsDataBaseTickersInnerConvertedLast } from './coins-data-base-tickers-inner-converted-last';


export interface CoinsTickersTickersInner { 
    /**
     * coin ticker base currency
     */
    base?: string;
    /**
     * coin ticker target currency
     */
    target?: string;
    market?: CoinsTickersTickersInnerMarket;
    /**
     * coin ticker last price
     */
    last?: number;
    /**
     * coin ticker volume
     */
    volume?: number;
    /**
     * coin ticker cost to move up in usd
     */
    cost_to_move_up_usd?: number;
    /**
     * coin ticker cost to move down in usd
     */
    cost_to_move_down_usd?: number;
    converted_last?: CoinsDataBaseTickersInnerConvertedLast;
    converted_volume?: CoinsDataBaseTickersInnerConvertedVolume;
    /**
     * coin ticker trust score
     */
    trust_score?: string;
    /**
     * coin ticker bid ask spread percentage
     */
    bid_ask_spread_percentage?: number;
    /**
     * coin ticker timestamp
     */
    timestamp?: string;
    /**
     * coin ticker last traded timestamp
     */
    last_traded_at?: string;
    /**
     * coin ticker last fetch timestamp
     */
    last_fetch_at?: string;
    /**
     * coin ticker anomaly
     */
    is_anomaly?: boolean;
    /**
     * coin ticker stale
     */
    is_stale?: boolean;
    /**
     * coin ticker trade url
     */
    trade_url?: string;
    /**
     * coin ticker token info url
     */
    token_info_url?: string | null;
    /**
     * coin ticker base currency coin id
     */
    coin_id?: string;
    /**
     * coin ticker target currency coin id
     */
    target_coin_id?: string;
}

