/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompaniesTreasuryCompaniesInner } from './companies-treasury-companies-inner';


export interface CompaniesTreasury { 
    /**
     * total btc/eth holdings of companies
     */
    total_holdings?: number;
    /**
     * total btc/eth holdings value in usd
     */
    total_value_usd?: number;
    /**
     * market cap dominance
     */
    market_cap_dominance?: number;
    companies?: Array<CompaniesTreasuryCompaniesInner>;
}

