/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoinsTickersTickersInner } from './coins-tickers-tickers-inner';


export interface ExchangeData { 
    /**
     * exchange name
     */
    name?: string;
    /**
     * exchange established year
     */
    year_established?: number;
    /**
     * exchange incorporated country
     */
    country?: string;
    /**
     * exchange description
     */
    description?: string;
    /**
     * exchange website url
     */
    url?: string;
    /**
     * exchange image url
     */
    image?: string;
    /**
     * exchange facebook url
     */
    facebook_url?: string;
    /**
     * exchange reddit url
     */
    reddit_url?: string;
    /**
     * exchange telegram url
     */
    telegram_url?: string;
    /**
     * exchange slack url
     */
    slack_url?: string;
    other_url_1?: string;
    other_url_2?: string;
    /**
     * exchange twitter handle
     */
    twitter_handle?: string;
    /**
     * exchange trading incentive
     */
    has_trading_incentive?: boolean;
    /**
     * exchange type (true for centralized, false for decentralized)
     */
    centralized?: boolean;
    /**
     * public notice for exchange
     */
    public_notice?: string;
    /**
     * alert notice for exchange
     */
    alert_notice?: string;
    /**
     * exchange trust score
     */
    trust_score?: number;
    /**
     * exchange trust score rank
     */
    trust_score_rank?: number;
    trade_volume_24h_btc?: number;
    /**
     * normalized trading volume by traffic in BTC in 24 hours <br>*refers to [`this blog`](https://blog.coingecko.com/trust-score/).
     */
    trade_volume_24h_btc_normalized?: number;
    /**
     * list of tickers
     */
    tickers?: Array<CoinsTickersTickersInner>;
}

