/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cryptocurrencies market cap percentage
 */
export interface GlobalDataMarketCapPercentage { 
    btc?: number;
    eth?: number;
}

