/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlobalData } from './global-data';


export interface Global { 
    data?: GlobalData;
    /**
     * cryptocurrencies market cap change percentage in 24 hours in usd
     */
    market_cap_change_percentage_24h_usd?: number;
    updated_at?: number;
}

