/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * nft collection volume in 24 hours percentage change
 */
export interface NFTDataVolume24hPercentageChange { 
    usd?: number;
    native_currency?: number;
}

