/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * nft collection floor price
 */
export interface NFTDataFloorPrice { 
    native_currency?: number;
    usd?: number;
}

