/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * nft collection links
 */
export interface NFTDataLinks { 
    homepage?: string;
    twitter?: string;
    discord?: string;
}

