/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchNftsInner { 
    /**
     * nft collection id
     */
    id?: string;
    /**
     * nft name
     */
    name?: string;
    /**
     * nft collection symbol
     */
    symbol?: string;
    /**
     * nft collection thumb image url
     */
    thumb?: string;
}

