/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchExchangesInner { 
    /**
     * exchange id
     */
    id?: string;
    /**
     * exchange name
     */
    name?: string;
    /**
     * exchange market type
     */
    market_type?: string;
    /**
     * exchange thumb image url
     */
    thumb?: string;
    /**
     * exchange large image url
     */
    large?: string;
}

