/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SimplePrice { 
    /**
     * price in USD
     */
    usd?: number;
    /**
     * market cap in USD
     */
    usd_market_cap?: number;
    /**
     * 24h volume in USD
     */
    usd_24h_vol?: number;
    /**
     * 24h change in USD
     */
    usd_24h_change?: number;
    /**
     * last updated timestamp
     */
    last_updated_at?: number;
}

