/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimplePrice } from './simple-price';


export interface SimpleTokenPrice200Response { 
    '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599'?: SimplePrice;
}

