/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendingSearchCoinsInner } from './trending-search-coins-inner';
import { TrendingSearchCategoriesInner } from './trending-search-categories-inner';
import { TrendingSearchNftsInner } from './trending-search-nfts-inner';


export interface TrendingSearch { 
    coins?: Array<TrendingSearchCoinsInner>;
    nfts?: Array<TrendingSearchNftsInner>;
    categories?: Array<TrendingSearchCategoriesInner>;
}

