/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * category market cap change percentage in 24 hours
 */
export interface TrendingSearchCategoriesInnerDataMarketCapChangePercentage24h { 
    btc?: number;
    usd?: number;
}

