export * from './asset-platforms.service';
import { AssetPlatformsService } from './asset-platforms.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './coins.service';
import { CoinsService } from './coins.service';
export * from './companies-beta.service';
import { CompaniesBetaService } from './companies-beta.service';
export * from './contract.service';
import { ContractService } from './contract.service';
export * from './derivatives.service';
import { DerivativesService } from './derivatives.service';
export * from './exchange-rates.service';
import { ExchangeRatesService } from './exchange-rates.service';
export * from './exchanges.service';
import { ExchangesService } from './exchanges.service';
export * from './global.service';
import { GlobalService } from './global.service';
export * from './nfts-beta.service';
import { NFTsBetaService } from './nfts-beta.service';
export * from './ping.service';
import { PingService } from './ping.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './simple.service';
import { SimpleService } from './simple.service';
export * from './trending.service';
import { TrendingService } from './trending.service';
export const APIS = [AssetPlatformsService, CategoriesService, CoinsService, CompaniesBetaService, ContractService, DerivativesService, ExchangeRatesService, ExchangesService, GlobalService, NFTsBetaService, PingService, SearchService, SimpleService, TrendingService];
