/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * coin price sparkline in 7 days
 */
export interface CoinsMarketsSparklineIn7d {
    price?: Array<number>;
}
