/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * coin all time low (atl) change in percentage
 */
export interface CoinsDataBaseMarketDataAtlChangePercentage {
    btc?: number;
    eur?: number;
    usd?: number;
}
