/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * coin total trading volume in currency
 */
export interface CoinsDataBaseMarketDataTotalVolume {
    btc?: number;
    eur?: number;
    usd?: number;
}
