/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * coin community data
 */
export interface CoinsDataBaseCommunityData {
    /**
     * coin facebook likes
     */
    facebook_likes?: number;
    /**
     * coin twitter followers
     */
    twitter_followers?: number;
    /**
     * coin reddit average posts in 48 hours
     */
    reddit_average_posts_48h?: number;
    /**
     * coin reddit average comments in 48 hours
     */
    reddit_average_comments_48h?: number;
    /**
     * coin reddit subscribers
     */
    reddit_subscribers?: number;
    /**
     * coin reddit active accounts in 48 hours
     */
    reddit_accounts_active_48h?: number;
    /**
     * coin telegram channel user count
     */
    telegram_channel_user_count?: number;
}
