/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * coin community data
 */
export interface CoinsHistoricalDataCommunityData {
    /**
     * coin facebook likes
     */
    facebook_likes?: number;
    /**
     * coin twitter followers
     */
    twitter_followers?: number;
    /**
     * coin reddit average posts 48h
     */
    reddit_average_posts_48h?: number;
    /**
     * coin reddit average comments 48h
     */
    reddit_average_comments_48h?: number;
    /**
     * coin reddit subscribers
     */
    reddit_subscribers?: number;
    /**
     * coin reddit accounts active 48h
     */
    reddit_accounts_active_48h?: number;
}
