/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoinsHistoricalDataDeveloperDataCodeAdditionsDeletions4Weeks } from './coins-historical-data-developer-data-code-additions-deletions4-weeks';
/**
 * coin developer data
 */
export interface CoinsHistoricalDataDeveloperData {
    /**
     * coin repository forks
     */
    forks?: number;
    /**
     * coin repository stars
     */
    stars?: number;
    /**
     * coin repository subscribers
     */
    subscribers?: number;
    /**
     * coin repository total issues
     */
    total_issues?: number;
    /**
     * coin repository closed issues
     */
    closed_issues?: number;
    /**
     * coin repository pull requests merged
     */
    pull_requests_merged?: number;
    /**
     * coin repository pull request contributors
     */
    pull_request_contributors?: number;
    code_additions_deletions_4_weeks?: CoinsHistoricalDataDeveloperDataCodeAdditionsDeletions4Weeks;
    /**
     * coin commit count 4 weeks
     */
    commit_count_4_weeks?: number;
}
