/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DerivativesTickersList } from './derivatives-tickers-list';
export interface DerivativesExchangesID {
    /**
     * derivatives exchange name
     */
    name?: string;
    /**
     * derivatives exchange open interest in BTC
     */
    open_interest_btc?: number;
    /**
     * derivatives exchange trade volume in BTC in 24 hours
     */
    trade_volume_24h_btc?: string;
    /**
     * number of perpetual pairs in the derivatives exchange
     */
    number_of_perpetual_pairs?: number;
    /**
     * number of futures pairs in the derivatives exchange
     */
    number_of_futures_pairs?: number;
    /**
     * derivatives exchange image url
     */
    image?: string;
    /**
     * derivatives exchange established year
     */
    year_established?: number | null;
    /**
     * derivatives exchange incorporated country
     */
    country?: string | null;
    /**
     * derivatives exchange description
     */
    description?: string;
    /**
     * derivatives exchange website url
     */
    url?: string;
    tickers?: Array<DerivativesTickersList>;
}
