/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface ExchangeRatesRatesValue {
    /**
     * name of the currency
     */
    name?: string;
    /**
     * unit of the currency
     */
    unit?: string;
    /**
     * value of the currency
     */
    value?: number;
    /**
     * type of the currency
     */
    type?: string;
}
