/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GlobalDeFiData { 
    /**
     * defi market cap
     */
    defi_market_cap?: string;
    /**
     * eth market cap
     */
    eth_market_cap?: string;
    /**
     * defi to eth ratio
     */
    defi_to_eth_ratio?: string;
    /**
     * defi trading volume in 24 hours
     */
    trading_volume_24h?: string;
    /**
     * defi dominance
     */
    defi_dominance?: string;
    /**
     * defi top coin name
     */
    top_coin_name?: string;
    /**
     * defi top coin dominance
     */
    top_coin_defi_dominance?: number;
}

