/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * cryptocurrencies total volume
 */
export interface GlobalDataTotalVolume {
    btc?: number;
    eth?: number;
}
