/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NFTDataBannerImage } from './nft-data-banner-image';
import { NFTDataMarketCap } from './nft-data-market-cap';
import { NFTDataFloorPrice } from './nft-data-floor-price';
import { NFTDataFloorPrice7dPercentageChange } from './nft-data-floor-price7d-percentage-change';
import { NFTDataAthDate } from './nft-data-ath-date';
import { NFTDataImage } from './nft-data-image';
import { NFTDataFloorPrice24hPercentageChange } from './nft-data-floor-price24h-percentage-change';
import { NFTDataLinks } from './nft-data-links';
import { NFTDataExplorersInner } from './nft-data-explorers-inner';
import { NFTDataFloorPrice30dPercentageChange } from './nft-data-floor-price30d-percentage-change';
import { NFTDataMarketCap24hPercentageChange } from './nft-data-market-cap24h-percentage-change';
import { NFTDataFloorPrice60dPercentageChange } from './nft-data-floor-price60d-percentage-change';
import { NFTDataFloorPrice1yPercentageChange } from './nft-data-floor-price1y-percentage-change';
import { NFTDataAth } from './nft-data-ath';
import { NFTDataVolume24h } from './nft-data-volume24h';
import { NFTDataVolume24hPercentageChange } from './nft-data-volume24h-percentage-change';
import { NFTDataAthChangePercentage } from './nft-data-ath-change-percentage';
import { NFTDataFloorPrice14dPercentageChange } from './nft-data-floor-price14d-percentage-change';
export interface NFTData {
    /**
     * nft collection id
     */
    id?: string;
    /**
     * nft collection contract address
     */
    contract_address?: string;
    /**
     * nft collection asset platform id
     */
    asset_platform_id?: string;
    /**
     * nft collection name
     */
    name?: string;
    /**
     * nft collection symbol
     */
    symbol?: string;
    image?: NFTDataImage;
    banner_image?: NFTDataBannerImage;
    /**
     * nft collection description
     */
    description?: string;
    /**
     * nft collection native currency
     */
    native_currency?: string;
    /**
     * nft collection native currency symbol
     */
    native_currency_symbol?: string;
    floor_price?: NFTDataFloorPrice;
    market_cap?: NFTDataMarketCap;
    volume_24h?: NFTDataVolume24h;
    /**
     * nft collection floor price in usd 24 hours percentage change
     */
    floor_price_in_usd_24h_percentage_change?: number;
    floor_price_24h_percentage_change?: NFTDataFloorPrice24hPercentageChange;
    market_cap_24h_percentage_change?: NFTDataMarketCap24hPercentageChange;
    volume_24h_percentage_change?: NFTDataVolume24hPercentageChange;
    /**
     * number of unique address owning the nfts
     */
    number_of_unique_addresses?: number;
    /**
     * number of unique address owning the nfts 24 hours percentage change
     */
    number_of_unique_addresses_24h_percentage_change?: number;
    /**
     * nft collection volume in usd 24 hours percentage change
     */
    volume_in_usd_24h_percentage_change?: number;
    /**
     * nft collection total supply
     */
    total_supply?: number;
    /**
     * nft collection one day sales
     */
    one_day_sales?: number;
    /**
     * nft collection one day sales 24 hours percentage change
     */
    one_day_sales_24h_percentage_change?: number;
    /**
     * nft collection one day average sale price
     */
    one_day_average_sale_price?: number;
    /**
     * nft collection one day average sale price 24 hours percentage change
     */
    one_day_average_sale_price_24h_percentage_change?: number;
    links?: NFTDataLinks;
    floor_price_7d_percentage_change?: NFTDataFloorPrice7dPercentageChange;
    floor_price_14d_percentage_change?: NFTDataFloorPrice14dPercentageChange;
    floor_price_30d_percentage_change?: NFTDataFloorPrice30dPercentageChange;
    floor_price_60d_percentage_change?: NFTDataFloorPrice60dPercentageChange;
    floor_price_1y_percentage_change?: NFTDataFloorPrice1yPercentageChange;
    /**
     * nft collection block explorers links
     */
    explorers?: Array<NFTDataExplorersInner>;
    /**
     * nft collection user favorites count
     */
    user_favorites_count?: number;
    ath?: NFTDataAth;
    ath_change_percentage?: NFTDataAthChangePercentage;
    ath_date?: NFTDataAthDate;
}
