/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * nft collection floor price 60 days percentage change
 */
export interface NFTDataFloorPrice60dPercentageChange { 
    usd?: number;
    native_currency?: number;
}

