/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface NFTList {
    /**
     * nft collection id
     */
    id?: string;
    /**
     * nft collection contract address
     */
    contract_address?: string;
    /**
     * nft collection name
     */
    name?: string;
    /**
     * nft collection asset platform id
     */
    asset_platform_id?: string;
    /**
     * nft collection symbol
     */
    symbol?: string;
}
