/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * nft collection all time highs change percentage
 */
export interface NFTDataAthChangePercentage {
    native_currency?: number;
    usd?: number;
}
