/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface SearchCoinsInner {
    /**
     * coin id
     */
    id?: string;
    /**
     * coin name
     */
    name?: string;
    /**
     * coin api symbol
     */
    api_symbol?: string;
    /**
     * coin symbol
     */
    symbol?: string;
    /**
     * coin market cap rank
     */
    market_cap_rank?: number;
    /**
     * coin thumb image url
     */
    thumb?: string;
    /**
     * coin large image url
     */
    large?: string;
}
