/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendingSearchCategoriesInnerData } from './trending-search-categories-inner-data';
export interface TrendingSearchCategoriesInner {
    id?: number;
    /**
     * category name
     */
    name?: string;
    /**
     * category market cap 1 hour change
     */
    market_cap_1h_change?: number;
    /**
     * category web slug
     */
    slug?: string;
    /**
     * category number of coins
     */
    coins_count?: number;
    data?: TrendingSearchCategoriesInnerData;
}
