/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendingSearchNftsInnerData } from './trending-search-nfts-inner-data';
export interface TrendingSearchNftsInner {
    /**
     * nft collection id
     */
    id?: string;
    /**
     * nft collection name
     */
    name?: string;
    /**
     * nft collection symbol
     */
    symbol?: string;
    /**
     * nft collection thumb image url
     */
    thumb?: string;
    nft_contract_id?: number;
    /**
     * nft collection native currency symbol
     */
    native_currency_symbol?: string;
    /**
     * nft collection floor price in native currency
     */
    floor_price_in_native_currency?: number;
    /**
     * nft collection floor price 24 hours percentage change
     */
    floor_price_24h_percentage_change?: number;
    data?: TrendingSearchNftsInnerData;
}
