/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrendingSearchCategoriesInnerDataMarketCapChangePercentage24h } from './trending-search-categories-inner-data-market-cap-change-percentage24h';
export interface TrendingSearchCategoriesInnerData {
    /**
     * category market cap
     */
    market_cap?: number;
    /**
     * category market cap in btc
     */
    market_cap_btc?: number;
    /**
     * category total volume
     */
    total_volume?: number;
    /**
     * category total volume in btc
     */
    total_volume_btc?: number;
    market_cap_change_percentage_24h?: TrendingSearchCategoriesInnerDataMarketCapChangePercentage24h;
    /**
     * category sparkline image url
     */
    sparkline?: string;
}
