/**
 * CoinGecko Public API V3
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface TrendingSearchNftsInnerData {
    /**
     * nft collection floor price
     */
    floor_price?: string;
    /**
     * nft collection floor price in usd 24 hours percentage change
     */
    floor_price_in_usd_24h_percentage_change?: string;
    /**
     * nft collection volume in 24 hours
     */
    h24_volume?: string;
    /**
     * nft collection 24 hours average sale price
     */
    h24_average_sale_price?: string;
    /**
     * nft collection sparkline image url
     */
    sparkline?: string;
    content?: string;
}
