/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin repository url
 */
export interface CoinsDataBaseLinksReposUrl { 
    /**
     * coin github repository url
     */
    github?: Array<string>;
    /**
     * coin bitbucket repository url
     */
    bitbucket?: Array<string>;
}

