/**
 * CoinGecko Public API V3
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * coin 14d price change in currency
 */
export interface CoinsDataBaseMarketDataPriceChangePercentage14dInCurrency { 
    btc?: number;
    eur?: number;
    usd?: number;
}

