name: Publish Package to npmjs
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            # Setup Node.js and npm configuration
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            # Install dependencies and build the package if necessary
            - name: Install dependencies
              run: npm ci

            # Build the package
            - name: Build package
              run: npm run build
              
            # Publish to npm
            - run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}